# import raw CSV, process the file, write to new CSV

import pandas as pd
import re
import numpy as np
import os

#os.chdir('/var/www/FlaskApp/FlaskApp')

year_mapping = {'09':'FR', '10':'SO', '11':'JR', '12':'SR'}
gender_mapping = {'Boys': 'M', 'Men': 'M', 'Girls':'W', 'Women': 'W'}
high_school_mapping = {"AHS": "Alta High School",
                        "Ahs UT": "Alta High School",
                        "Alta": "Alta High School",
                        "Alta Hawks High School": "Alta High School",
                        "Alta High School ": "Alta High School",
                        "Alta High School A": "Alta High School",
                        "Alta High School-UT": "Alta High School",
                        "Alta High School-UT A": "Alta High School",
                        "Afhs": "American Fork High School",
                        "Afhs-UT": "American Fork High School",
                        "Am. Fork": "American Fork High School",
                        "American Fork": "American Fork High School",
                        "American Fork High Schoo": "American Fork High School",
                        "American Fork High Schoo A": "American Fork High School",
                        "American Fork High School ": "American Fork High School",
                        "American Fork High School A": "American Fork High School",
                        "American Fork High School-UT": "American Fork High School",
                        "American Fork High School-UT A": "American Fork High School",
                        "American Leadership Acad": "American Leadership Academy",
                        "American Leadership Academy A": "American Leadership Academy",
                        "Bear River": "Bear River High School",
                        "Bear River Bears": "Bear River High School",
                        "Bear River High School": "Bear River High School",
                        "Bear River High School ": "Bear River High School",
                        "Bear River High School A": "Bear River High School",
                        "Bear River High School-VA": "Bear River High School",
                        "Bear River High School-VA A": "Bear River High School",
                        "Ben Lomond": "Ben Lomond High School",
                        "Ben Lomond High": "Ben Lomond High School",
                        "Ben Lomond High A": "Ben Lomond High School",
                        "Ben Lomond High School": "Ben Lomond High School",
                        "Ben Lomond High School ": "Ben Lomond High School",
                        "Ben Lomond High School A": "Ben Lomond High School",
                        "Ben Lomond-VA": "Ben Lomond High School",
                        "Ben Lomond-VA A": "Ben Lomond High School",
                        "Blhs": "Ben Lomond High School",
                        "Scots": "Ben Lomond High School",
                        "Bingham": "Bingham High School",
                        "Bingham High School": "Bingham High School",
                        "Bingham High School ": "Bingham High School",
                        "Bingham High School A": "Bingham High School",
                        "Bingham High School-UT": "Bingham High School",
                        "Bingham High School-UT A": "Bingham High School",
                        "Bingham Miners": "Bingham High School",
                        "Bingham Miners A": "Bingham High School",
                        "Bingham-UT": "Bingham High School",
                        "Miners": "Bingham High School",
                        "BONN": "Bonneville High School",
                        "Bonneville": "Bonneville High School",
                        "Bonneville High School": "Bonneville High School",
                        "Bonneville High School ": "Bonneville High School",
                        "Bnftl": "Bountiful High School",
                        "BNTFL": "Bountiful High School",
                        "BNTFL-AK": "Bountiful High School",
                        "Bountiful": "Bountiful High School",
                        "Bountiful High School": "Bountiful High School",
                        "Bountiful High School ": "Bountiful High School",
                        "Bountiful High School A": "Bountiful High School",
                        "Bountiful-UT": "Bountiful High School",
                        "Braves": "Bountiful High School",
                        "BE": "Box Elder High School",
                        "BEHS": "Box Elder High School",
                        "Box Elder": "Box Elder High School",
                        "Box Elder High School": "Box Elder High School",
                        "Box Elder High School ": "Box Elder High School",
                        "Box Elder High School A": "Box Elder High School",
                        "Box Elder-AK": "Box Elder High School",
                        "Box Elder-UT": "Box Elder High School",
                        "A FR Brighton High School": "Brighton High School",
                        "A SO Brighton High School": "Brighton High School",
                        "Bengals": "Brighton High School",
                        "Bengals-UT": "Brighton High School",
                        "Brighton": "Brighton High School",
                        "Brighton High School": "Brighton High School",
                        "Brighton High School ": "Brighton High School",
                        "Brighton High School A": "Brighton High School",
                        "Brighton High School-UT": "Brighton High School",
                        "Brighton High School-UT A": "Brighton High School",
                        "Canyon View": "Canyon View High School",
                        "Canyon View High": "Canyon View High School",
                        "Canyon View High A": "Canyon View High School",
                        "Canyon View High School": "Canyon View High School",
                        "Canyon View High School ": "Canyon View High School",
                        "Canyon View High School A": "Canyon View High School",
                        "Canyonview": "Canyon View High School",
                        "Canyonview High School": "Canyon View High School",
                        "Canyonview High School A": "Canyon View High School",
                        "Canyonview High School-VA": "Canyon View High School",
                        "Canyonview High School-VA A": "Canyon View High School",
                        "Cvhs": "Canyon View High School",
                        "D Canyon View High": "Canyon View High School",
                        "J Canyon View High": "Canyon View High School",
                        "M Canyon View High": "Canyon View High School",
                        "S Canyon View High": "Canyon View High School",
                        "T Canyon View High": "Canyon View High School",
                        "Carbon": "Carbon High School",
                        "Carbon High School": "Carbon High School",
                        "Carbon High School A": "Carbon High School",
                        "Carbon High School-VA": "Carbon High School",
                        "Carbon High School-VA A": "Carbon High School",
                        "Dinos": "Carbon High School",
                        "Cedar City": "Cedar City High School",
                        "Cedar City High": "Cedar City High School",
                        "Cedar City High A": "Cedar City High School",
                        "Cedar City High School": "Cedar City High School",
                        "Cedar City High School ": "Cedar City High School",
                        "Cedar City High School A": "Cedar City High School",
                        "Cedar City High School-VA": "Cedar City High School",
                        "Cedar City High School-VA A": "Cedar City High School",
                        "CedarCity": "Cedar City High School",
                        "Redmen": "Cedar City High School",
                        "Clearfield High School": "Clearfield High School",
                        "Clearfield High School ": "Clearfield High School",
                        "Clear-UT": "Clearfield High School",
                        "Falcons": "Clearfield High School",
                        "Falcons-UT": "Clearfield High School",
                        "Chhs": "Copper Hills High School",
                        "Chhs-UT": "Copper Hills High School",
                        "Copper Hills": "Copper Hills High School",
                        "Copper Hills High School": "Copper Hills High School",
                        "Copper Hills High School ": "Copper Hills High School",
                        "Copper Hills High School A": "Copper Hills High School",
                        "Copper Hills High School-UT": "Copper Hills High School",
                        "Copper Hills High School-UT A": "Copper Hills High School",
                        "Corner Canyon High S": "Corner Canyon High School",
                        "Corner Canyon High S A": "Corner Canyon High School",
                        "Corner Canyon High School": "Corner Canyon High School",
                        "Corner Canyon High School ": "Corner Canyon High School",
                        "Colts": "Cottonwood High School",
                        "Colts-UT": "Cottonwood High School",
                        "Cottonwood": "Cottonwood High School",
                        "Cottonwood High School": "Cottonwood High School",
                        "Cottonwood High School ": "Cottonwood High School",
                        "Cottonwood High School A": "Cottonwood High School",
                        "Cottonwood High School-UT": "Cottonwood High School",
                        "Cottonwood High School-UT A": "Cottonwood High School",
                        "Cottonwood-UT": "Cottonwood High School",
                        "Cyp": "Cyprus High School",
                        "Cyprus": "Cyprus High School",
                        "Cyprus High School": "Cyprus High School",
                        "Cyprus High School ": "Cyprus High School",
                        "Cyprus High School A": "Cyprus High School",
                        "Cyprus-UT": "Cyprus High School",
                        "Davis": "Davis High School",
                        "Davis High School": "Davis High School",
                        "Davis High School ": "Davis High School",
                        "Davis High School A": "Davis High School",
                        "Davis High School-UT": "Davis High School",
                        "Davis High School-UT A": "Davis High School",
                        "Delta": "Delta High School",
                        "Delta High School": "Delta High School",
                        "Delta High School A": "Delta High School",
                        "Delta High School-VA": "Delta High School",
                        "Delta High School-VA A": "Delta High School",
                        "Rabbits": "Delta High School",
                        "Desert Hills": "Desert Hills High School",
                        "Desert Hills High School": "Desert Hills High School",
                        "Desert Hills High School ": "Desert Hills High School",
                        "Desert Hills High School A": "Desert Hills High School",
                        "Desert Hills High School-VA": "Desert Hills High School",
                        "Desert Hills High School-VA A": "Desert Hills High School",
                        "Dhs-UT": "Desert Hills High School",
                        "Dixie": "Dixie High School",
                        "Dixie Flyers": "Dixie High School",
                        "Dixie High School": "Dixie High School",
                        "Dixie High School ": "Dixie High School",
                        "Dixie High School A": "Dixie High School",
                        "Dixie-AK": "Dixie High School",
                        "Dixie-UT": "Dixie High School",
                        "East": "East High School",
                        "East High School": "East High School",
                        "East High School ": "East High School",
                        "East High School A": "East High School",
                        "East High School Leopards": "East High School",
                        "East High School Leopards A": "East High School",
                        "East-AK": "East High School",
                        "East-UT": "East High School",
                        "Emery": "Emery High School",
                        "Emery High School": "Emery High School",
                        "Emery High School A": "Emery High School",
                        "Emery High School-UT": "Emery High School",
                        "Emery High School-UT A": "Emery High School",
                        "FHS-UT": "Fremont High School",
                        "Fremont": "Fremont High School",
                        "Fremont High School": "Fremont High School",
                        "Fremont High School ": "Fremont High School",
                        "Fremont High School A": "Fremont High School",
                        "Fremont High School-UT": "Fremont High School",
                        "Fremont High School-UT A": "Fremont High School",
                        "Ghs Swimming-VA": "Gainesville High School",
                        "Grand County High Schoo": "Grand County High School",
                        "Grand County High Schoo A": "Grand County High School",
                        "Grand County High School": "Grand County High School",
                        "Granger High School": "Granger High School",
                        "Granger High School ": "Granger High School",
                        "Ghs": "Grantsville High School",
                        "Ghs Swimming-VA A": "Grantsville High School",
                        "Grantsville": "Grantsville High School",
                        "Grantsville High School": "Grantsville High School",
                        "Grantsville High School A": "Grantsville High School",
                        "Green Canyon High School": "Green Canyon High School",
                        "Green Canyon High School ": "Green Canyon High School",
                        "Gunnison Valley High Scho": "Gunnison Valley High School",
                        "Gunnison Valley High School": "Gunnison Valley High School",
                        "Herriman High School": "Herriman High School",
                        "Herriman High School ": "Herriman High School",
                        "Herriman High School A": "Herriman High School",
                        "HIGH": "Highland High School",
                        "Highland": "Highland High School",
                        "Highland High School": "Highland High School",
                        "Highland High School ": "Highland High School",
                        "Highland High School A": "Highland High School",
                        "Highland-AK": "Highland High School",
                        "Highland-UT": "Highland High School",
                        "Hillcrest": "Hillcrest High School",
                        "Hillcrest High High School": "Hillcrest High School",
                        "Hillcrest High High School A": "Hillcrest High School",
                        "Hillcrest High School": "Hillcrest High School",
                        "Hillcrest High School ": "Hillcrest High School",
                        "Hillcrest High School A": "Hillcrest High School",
                        "HILL-UT": "Hillcrest High School",
                        "Huskies": "Hillcrest High School",
                        "Hunter": "Hunter High School",
                        "Hunter High School": "Hunter High School",
                        "Hunter High School ": "Hunter High School",
                        "Hunter High School A": "Hunter High School",
                        "Hunter High School-UT": "Hunter High School",
                        "Hunter High School-UT A": "Hunter High School",
                        "Wolverines": "Hunter High School",
                        "Wolverines-UT": "Hunter High School",
                        "Hurricane": "Hurricane High School",
                        "Hurricane High School": "Hurricane High School",
                        "Hurricane High School ": "Hurricane High School",
                        "Hurricane High School A": "Hurricane High School",
                        "Hurricane High School-VA": "Hurricane High School",
                        "Hurricane High School-VA A": "Hurricane High School",
                        "ICS": "Intermountain Christian School",
                        "Inter Mtn": "Intermountain Christian School",
                        "Intermountain Christian High": "Intermountain Christian School",
                        "Intermountain Christian School": "Intermountain Christian School",
                        "Intermountain Christian School-VA": "Intermountain Christian School",
                        "Intermountian": "Intermountain Christian School",
                        "JOR": "Jordan High School",
                        "Jordan": "Jordan High School",
                        "Jordan High School": "Jordan High School",
                        "Jordan High School ": "Jordan High School",
                        "Jordan High School A": "Jordan High School",
                        "Jordan High School-UT": "Jordan High School",
                        "FR Juan Diego High School": "Juan Diego Catholic High School",
                        "Jdchs": "Juan Diego Catholic High School",
                        "Juan Deigo": "Juan Diego Catholic High School",
                        "Juan Diego": "Juan Diego Catholic High School",
                        "Juan Diego Catholic High Schoo": "Juan Diego Catholic High School",
                        "Juan Diego Catholic High Schoo A": "Juan Diego Catholic High School",
                        "Juan Diego Catholic High School": "Juan Diego Catholic High School",
                        "Juan Diego Catholic High Schoo-UT": "Juan Diego Catholic High School",
                        "Juan Diego Catholic High Schoo-UT A": "Juan Diego Catholic High School",
                        "Juan Diego High Schoo": "Juan Diego Catholic High School",
                        "Juan Diego High Schoo A": "Juan Diego Catholic High School",
                        "Juan Diego High School": "Juan Diego Catholic High School",
                        "JUDG": "Judge Memorial High School",
                        "Judge": "Judge Memorial High School",
                        "Judge Memorial": "Judge Memorial High School",
                        "Judge Memorial Catholic High S": "Judge Memorial High School",
                        "Judge Memorial Catholic High S A": "Judge Memorial High School",
                        "Judge Memorial Catholic High S-UT": "Judge Memorial High School",
                        "Judge Memorial Catholic High S-UT A": "Judge Memorial High School",
                        "Judge Memorial High School": "Judge Memorial High School",
                        "Judge Memorial High School A": "Judge Memorial High School",
                        "Kearns": "Kearns High School",
                        "Kearns Cougars": "Kearns High School",
                        "Kearns Cougars-UT": "Kearns High School",
                        "Kearns High School": "Kearns High School",
                        "Kearns High School ": "Kearns High School",
                        "Kearns High School A": "Kearns High School",
                        "Kearns High School-UT": "Kearns High School",
                        "Kearns High School-UT A": "Kearns High School",
                        "LAYTN": "Layton High School",
                        "LAYTN-UT": "Layton High School",
                        "Layton": "Layton High School",
                        "Layton High School": "Layton High School",
                        "Layton High School ": "Layton High School",
                        "Layton High School A": "Layton High School",
                        "Layton High School-UT": "Layton High School",
                        "Lehi": "Lehi High School",
                        "Lehi High School": "Lehi High School",
                        "Lehi High School ": "Lehi High School",
                        "Lehi High School A": "Lehi High School",
                        "Lehi High School-UT": "Lehi High School",
                        "Lehi High School-UT A": "Lehi High School",
                        "Lehi-AK": "Lehi High School",
                        "Logan": "Logan High School",
                        "Logan High School": "Logan High School",
                        "Logan High School ": "Logan High School",
                        "Logan High School A": "Logan High School",
                        "Logan-AK": "Logan High School",
                        "SR Logan High School": "Logan High School",
                        "Knights-UT": "Lone Peak High School",
                        "Lone Peak": "Lone Peak High School",
                        "Lone Peak High School": "Lone Peak High School",
                        "Lone Peak High School ": "Lone Peak High School",
                        "Lone Peak High School A": "Lone Peak High School",
                        "Lone Peak High School-UT": "Lone Peak High School",
                        "Lone Peak High School-UT A": "Lone Peak High School",
                        "Lone Peak-UT": "Lone Peak High School",
                        "Lphs": "Lone Peak High School",
                        "Maeser Prep High School": "Maeser Prep High School",
                        "Maeser Prep High Shcool": "Maeser Prep High School",
                        "Maple Mountain High School": "Maple Mountain High School",
                        "Maple Mountain High School ": "Maple Mountain High School",
                        "Maple Mountain High School A": "Maple Mountain High School",
                        "Maple Mountain-AK": "Maple Mountain High School",
                        "MHS": "Millard High School",
                        "Millard High School": "Millard High School",
                        "Morgan High High School": "Morgan High School",
                        "MCHS": "Mountain Crest High School",
                        "Mountain Crest": "Mountain Crest High School",
                        "Mountain Crest High School": "Mountain Crest High School",
                        "Mountain Crest High School ": "Mountain Crest High School",
                        "Mountain Crest High School A": "Mountain Crest High School",
                        "Mountain Crest-UT": "Mountain Crest High School",
                        "Mt Crest-AK": "Mountain Crest High School",
                        "Mountain View": "Mountain View High School",
                        "Mountain View High School": "Mountain View High School",
                        "Mountain View High School ": "Mountain View High School",
                        "Mountain View High School A": "Mountain View High School",
                        "Mountain View-UT": "Mountain View High School",
                        "Mt View-AK": "Mountain View High School",
                        "Mtn View": "Mountain View High School",
                        "Mvhs": "Mountain View High School",
                        "Murray": "Murray High School",
                        "Murray High School": "Murray High School",
                        "Murray High School ": "Murray High School",
                        "Murray High School A": "Murray High School",
                        "Murray-UT": "Murray High School",
                        "Spartans": "Murray High School",
                        "North Sanpete High School": "North Sanpete High School",
                        "NSHS": "North Sanpete High School",
                        "North Summit": "North Summit High",
                        "North Summit High": "North Summit High",
                        "North Summit High Schoo": "North Summit High",
                        "North Summit High School": "North Summit High",
                        "North Summit High School A": "North Summit High",
                        "North Summit HS": "North Summit High",
                        "North Summit HS A": "North Summit High",
                        "North Summit-VA": "North Summit High",
                        "North Summit-VA A": "North Summit High",
                        "NORTH": "Northridge High School",
                        "Northridge": "Northridge High School",
                        "Northridge High School": "Northridge High School",
                        "Northridge High School ": "Northridge High School",
                        "Northridge High School A": "Northridge High School",
                        "Northridge High School-UT": "Northridge High School",
                        "OAKL": "Oakley High School",
                        "Oakley": "Oakley High School",
                        "Oakley High School": "Oakley High School",
                        "Oakley High School A": "Oakley High School",
                        "Oakley School": "Oakley High School",
                        "Oakley School A": "Oakley High School",
                        "Ogden": "Ogden High School",
                        "Ogden High School": "Ogden High School",
                        "Ogden High School A": "Ogden High School",
                        "Ogden High Swimming": "Ogden High School",
                        "Ogden High Swimming ": "Ogden High School",
                        "Ogden-AK": "Ogden High School",
                        "Ohs Tigers": "Ogden High School",
                        "Tigers": "Ogden High School",
                        "Oly": "Olympus High School",
                        "Olympus": "Olympus High School",
                        "Olympus High School": "Olympus High School",
                        "Olympus High School ": "Olympus High School",
                        "Olympus High School A": "Olympus High School",
                        "Olympus-AK": "Olympus High School",
                        "Olympus-UT": "Olympus High School",
                        "OREM": "Orem High School",
                        "Orem High School": "Orem High School",
                        "Orem High School ": "Orem High School",
                        "Orem High School A": "Orem High School",
                        "Orem High School Tigers": "Orem High School",
                        "Orem High School Tigers A": "Orem High School",
                        "Orem-AK": "Orem High School",
                        "Orem-UT": "Orem High School",
                        "Park": "Park City High School",
                        "Park City": "Park City High School",
                        "Park City High School": "Park City High School",
                        "Park City High School ": "Park City High School",
                        "Park City High School A": "Park City High School",
                        "Park City High School-VA": "Park City High School",
                        "Park City High School-VA A": "Park City High School",
                        "ParkCity": "Park City High School",
                        "Parowan": "Parowan High School",
                        "Payson High School": "Payson High School",
                        "Payson High School ": "Payson High School",
                        "Payson High School A": "Payson High School",
                        "Pine View": "Pine View High School",
                        "Pine View High Schoool": "Pine View High School",
                        "Pine View-UT": "Pine View High School",
                        "PineView": "Pine View High School",
                        "PineView High School": "Pine View High School",
                        "PineView High School ": "Pine View High School",
                        "PineView High School A": "Pine View High School",
                        "PineView-AK": "Pine View High School",
                        "Pghs": "Pleasant Grove High School",
                        "Pleasant Grove": "Pleasant Grove High School",
                        "Pleasant Grove High School": "Pleasant Grove High School",
                        "Pleasant Grove High School ": "Pleasant Grove High School",
                        "Pleasant Grove High School A": "Pleasant Grove High School",
                        "Pleasant Grove High School-UT": "Pleasant Grove High School",
                        "Pleasant Grove High School-UT A": "Pleasant Grove High School",
                        "Provo": "Provo High School",
                        "Provo High School": "Provo High School",
                        "Provo High School ": "Provo High School",
                        "Provo High School A": "Provo High School",
                        "PROVO-AK": "Provo High School",
                        "Provo-UT": "Provo High School",
                        "Richfield": "Richfield High School",
                        "Richfield High School": "Richfield High School",
                        "Richfield High School A": "Richfield High School",
                        "Richfield High School Wildcats-VA": "Richfield High School",
                        "Richfield High School Wildcats-VA A": "Richfield High School",
                        "Wildcats": "Richfield High School",
                        "Ridgeline High School": "Ridgeline High School",
                        "Ridgeline High School ": "Ridgeline High School",
                        "Riverton": "Riverton High School",
                        "Riverton High School": "Riverton High School",
                        "Riverton High School ": "Riverton High School",
                        "Riverton High School A": "Riverton High School",
                        "Riverton High School-UT": "Riverton High School",
                        "Riverton High School-UT A": "Riverton High School",
                        "RH": "Rowland Hall High School",
                        "Rhsm": "Rowland Hall High School",
                        "Rowland Hall": "Rowland Hall High School",
                        "Rowland Hall High School": "Rowland Hall High School",
                        "Rowland Hall High School A": "Rowland Hall High School",
                        "Rowland Hall HS": "Rowland Hall High School",
                        "Rowland Hall HS A": "Rowland Hall High School",
                        "Rowland Hall St. Marks": "Rowland Hall High School",
                        "Rowland Hall St. Marks A": "Rowland Hall High School",
                        "Rowland Hall St. Marks-VA": "Rowland Hall High School",
                        "Rowland Hall St. Marks-VA A": "Rowland Hall High School",
                        "RHS": "Roy High School",
                        "Roy": "Roy High School",
                        "Roy High School": "Roy High School",
                        "Roy High School ": "Roy High School",
                        "Roy High School A": "Roy High School",
                        "Royals": "Roy High School",
                        "Roy-UT": "Roy High School",
                        "Saint Joseph High School": "Saint Joseph High School",
                        "Salem Hills": "Salem Hills High School",
                        "Salem Hills High School": "Salem Hills High School",
                        "Salem Hills High School ": "Salem Hills High School",
                        "Salem Hills High School A": "Salem Hills High School",
                        "Salt Lake Lutheran High School-VA": "Salt Lake Lutheran High School",
                        "Sky View": "Sky View High School",
                        "Sky View High School": "Sky View High School",
                        "Sky View High School ": "Sky View High School",
                        "Sky View High School A": "Sky View High School",
                        "Sky View-AK": "Sky View High School",
                        "Sky View-UT": "Sky View High School",
                        "SV": "Sky View High School",
                        "SVHS": "Sky View High School",
                        "R JR Skyline High School": "Skyline High School",
                        "R SO Skyline High School": "Skyline High School",
                        "R SR Skyline High School": "Skyline High School",
                        "Skyline": "Skyline High School",
                        "Skyline High School": "Skyline High School",
                        "Skyline High School A": "Skyline High School",
                        "Skyline Swim Team": "Skyline High School",
                        "Skyridge High School": "Skyline High School",
                        "Skyridge High School ": "Skyline High School",
                        "SKY-UT": "Skyline High School",
                        "Snow Canyon": "Snow Canyon High School",
                        "Snow Canyon High School": "Snow Canyon High School",
                        "Snow Canyon High School ": "Snow Canyon High School",
                        "Snow Canyon High School A": "Snow Canyon High School",
                        "Snow Canyon-AK": "Snow Canyon High School",
                        "Snow Canyon-UT": "Snow Canyon High School",
                        "South Sevier High School": "South Sevier High School",
                        "South Summit": "South Summit High School",
                        "South Summit High School": "South Summit High School",
                        "South Summit High School Swim": "South Summit High School",
                        "South Summit High School Swim A": "South Summit High School",
                        "SSHS": "South Summit High School",
                        "Sfhs": "Spanish Fork High School",
                        "Spanish Fork": "Spanish Fork High School",
                        "Spanish Fork High": "Spanish Fork High School",
                        "Spanish Fork High A": "Spanish Fork High School",
                        "Spanish Fork High School": "Spanish Fork High School",
                        "Spanish Fork High School ": "Spanish Fork High School",
                        "Spanish Fork High School A": "Spanish Fork High School",
                        "Spanish Fork-AK": "Spanish Fork High School",
                        "SpanishFork": "Spanish Fork High School",
                        "Red Devlis": "Springville High School",
                        "Springville": "Springville High School",
                        "Springville High School": "Springville High School",
                        "Springville High School ": "Springville High School",
                        "Springville High School A": "Springville High School",
                        "Springville-AK": "Springville High School",
                        "Springville-UT": "Springville High School",
                        "SPRV": "Springville High School",
                        "Stanbury High School": "Stansbury High School",
                        "Stanbury High School A": "Stansbury High School",
                        "Stansbury High School": "Stansbury High School",
                        "Stansbury High School ": "Stansbury High School",
                        "Stansbury High School A": "Stansbury High School",
                        "Stansbury-AK": "Stansbury High School",
                        "Summit Academy High School": "Summit Academy High School",
                        "Summit Academy High School A": "Summit Academy High School",
                        "Syr": "Syracuse High School",
                        "Syracuse": "Syracuse High School",
                        "Syracuse High School": "Syracuse High School",
                        "Syracuse High School ": "Syracuse High School",
                        "Syracuse High School Swimiming": "Syracuse High School",
                        "Syracuse High School-UT": "Syracuse High School",
                        "Syracuse High School-UT A": "Syracuse High School",
                        "Tayl": "Taylorsville High School",
                        "Taylorsville": "Taylorsville High School",
                        "Taylorsville High School": "Taylorsville High School",
                        "Taylorsville High School ": "Taylorsville High School",
                        "Taylorsville High School A": "Taylorsville High School",
                        "Taylorsville High School-UT": "Taylorsville High School",
                        "Taylorsville High School-UT A": "Taylorsville High School",
                        "Ths": "Taylorsville High School",
                        "T-Ville": "Taylorsville High School",
                        "Telos Academy": "Telos Academy High School",
                        "Telos Academy High School": "Telos Academy High School",
                        "Timpanogos High Schol": "Timpanogos High School",
                        "Timpanogos High Schol A": "Timpanogos High School",
                        "Timp": "Timpview High School",
                        "Timpview": "Timpview High School",
                        "Timpview High School": "Timpview High School",
                        "Timpview High School ": "Timpview High School",
                        "Timpview High School A": "Timpview High School",
                        "Timpview-AK": "Timpview High School",
                        "Timpview-UT": "Timpview High School",
                        "Tooele": "Tooele High School",
                        "Tooele High School": "Tooele High School",
                        "Tooele High School ": "Tooele High School",
                        "Tooele High School A": "Tooele High School",
                        "Tooele-AK": "Tooele High School",
                        "Tooele-UT": "Tooele High School",
                        "Uintah": "Uintah High School",
                        "Uintah High School": "Uintah High School",
                        "Uintah High School ": "Uintah High School",
                        "Uintah High School A": "Uintah High School",
                        "Uintah High School Swim Team": "Uintah High School",
                        "Uintah High School Swim Team A": "Uintah High School",
                        "Uintah-AK": "Uintah High School",
                        "Utes": "Uintah High School",
                        "Union High School": "Union High School",
                        "Vhs": "Viewmont High School",
                        "Viewmont": "Viewmont High School",
                        "Viewmont High School": "Viewmont High School",
                        "Viewmont High School ": "Viewmont High School",
                        "Viewmont High School A": "Viewmont High School",
                        "Viewmont HighSchool-UT": "Viewmont High School",
                        "Viewmont HighSchool-UT A": "Viewmont High School",
                        "Vikings": "Viewmont High School",
                        "Vikings-UT": "Viewmont High School",
                        "Wasatch Academy High Sch": "Wasatch Academy High School",
                        "Wasatch Academy High School": "Wasatch Academy High School",
                        "Wasatch Academy Swim Team": "Wasatch Academy High School",
                        "WASA": "Wasatch High School",
                        "Wasatch": "Wasatch High School",
                        "Wasatch High School": "Wasatch High School",
                        "Wasatch High School ": "Wasatch High School",
                        "Wasatch High School A": "Wasatch High School",
                        "Wasatch High School-VA": "Wasatch High School",
                        "Wasatch High School-VA A": "Wasatch High School",
                        "Waterford": "Waterford High School",
                        "Waterford High School": "Waterford High School",
                        "Waterford High School A": "Waterford High School",
                        "Waterford High School-VA": "Waterford High School",
                        "WTFD": "Waterford High School",
                        "Weber": "Weber High School",
                        "Weber High School": "Weber High School",
                        "Weber High School ": "Weber High School",
                        "Weber High School A": "Weber High School",
                        "Weber High School-UT": "Weber High School",
                        "Weber High School-UT A": "Weber High School",
                        "West": "West High School",
                        "West High School": "West High School",
                        "West High School ": "West High School",
                        "West High School A": "West High School",
                        "West High School-UT": "West High School",
                        "West High School-UT A": "West High School",
                        "West-UT": "West High School",
                        "West Jordan": "West Jordan High School",
                        "West Jordan High School": "West Jordan High School",
                        "West Jordan High School A": "West Jordan High School",
                        "West Jordan High School-UT": "West Jordan High School",
                        "West Jordan High School-UT A": "West Jordan High School",
                        "WJ": "West Jordan High School",
                        "WJ-UT": "West Jordan High School",
                        "West Lake-AK": "Westlake High School",
                        "Westlake High School": "Westlake High School",
                        "Westlake High School ": "Westlake High School",
                        "Westlake High School A": "Westlake High School",
                        "R SR Woods Cross High School": "Woods Cross High School",
                        "Woods Cross": "Woods Cross High School",
                        "Woods Cross High School": "Woods Cross High School",
                        "Woods Cross High School ": "Woods Cross High School",
                        "Woods Cross High School A": "Woods Cross High School",
                        "Woods Cross-AK": "Woods Cross High School",
                        "Woods Cross-UT": "Woods Cross High School",
                        "Wxhs": "Woods Cross High School",
                        }


# Read in initial data sets from CSV.
df_SV_raw = pd.read_csv('data/swimming_data.csv')
df_State_raw = pd.read_csv('data/swimming_data_state.csv')
df_State_raw = df_State_raw[np.isfinite(df_State_raw['key'])]


# Define CSV cleanup and processing methods
def cleanup_SV(df_SV_raw):
    df_SV_raw['Year'] = pd.DatetimeIndex(df_SV_raw['Date']).year
    df_SV_raw = df_SV_raw[['Event', 'Time Full', 'Year', 'Swimmer', 'Gender']]
    return df_SV_raw


def cleanup_state(df_State_raw):
    df_State_raw = process_place(df_State_raw)
    df_State_raw = process_school_year(df_State_raw)
    df_State_raw = process_gender(df_State_raw)
    df_State_raw = process_times(df_State_raw)
    df_State_raw = process_school_name(df_State_raw)
    return df_State_raw


def process_school_name(df_State_raw):
    df_State_raw['School'] = df_State_raw['School'].apply(lambda x: x.strip())
    df_State_raw['School'] = df_State_raw['School'].apply(
        lambda x: high_school_mapping[x] if x in high_school_mapping else x)
    return df_State_raw


def process_place(df_State_raw):
    # Fill NA with 0 and convert col to int format
    df_State_raw['Place'] = df_State_raw['Place'].fillna(0)
    df_State_raw['Place'] = df_State_raw['Place'].apply(lambda x: int(x))
    return df_State_raw


def process_school_year(df_State_raw):
    # Standardize school year formatting
    # Remove school year when it appears in school name col 'School'
    df_State_raw['Year'] = df_State_raw['Year'].fillna('NA')
    df_State_raw['Year'] = df_State_raw['Year'].apply(lambda x: '09' if x=='9' else x)
    school_years = [' FR ',' SO ',' JR ',' SR ',' 09 ',' 10 ',' 11 ',' 12 ']
    df_State_raw['Year'] = df_State_raw['Year'].apply(
            lambda x: x if any(x == year for year in map(str.strip, school_years)) else 'NA')
    for index, row in df_State_raw.iterrows():
        if pd.isnull(row['School']):
            continue
        else:
            school_name = row['School']
            for year in school_years:
                if year in school_name:
                    if row['Year'] not in map(str.strip, school_years):
                        df_State_raw.loc[index, 'Year'] = year.strip()
                    df_State_raw.loc[index, 'School'] = school_name[school_name.find(year)+4:]
                    break
    df_State_raw['Year'].replace(year_mapping, inplace=True)
    return df_State_raw


def process_gender(df_State_raw):
    # Standardize gender formatting
    df_State_raw['Gender'].replace(gender_mapping, inplace=True)
    return df_State_raw


def sub_chars(x):
    if x is not None:
        if len(re.findall('\d', x)) > 0:
            x = re.sub("[^0-9\.\:]", "", x)
        else:
            x = ''
    else:
        x = ''
    return x

def process_times(df_State_raw):
    # Times come in text format
    # Convert times to time obj
    # also extract seconds and minutes values, write those values to new col
    df_State_raw['Final Time'] = df_State_raw['Final Time'].fillna(value='')
    df_State_raw['time_cleanup'] = df_State_raw['Final Time'].apply(
            lambda x: sub_chars(x))
    df_State_raw['time_split'] = df_State_raw['time_cleanup'].apply(
            lambda x: x.split(":"))
    df_State_raw['time_seconds'] = df_State_raw['time_split'].apply(
            lambda x: 999.9 if len(x[0]) == 0 else (float(x[0])
            if len(x) == 1 else 60 * float(x[0]) + float(x[1])))
    df_State_raw['time_str'] = df_State_raw['time_split'].apply(
            lambda x: '2000-01-01 00:59:59.99' if len(x[0]) == 0 else ('2000-01-01 00:00:' + x[0]
            if len(x) == 1 else '2000-01-01 00:0' +x[0] + ':' + x[1]))
    df_State_raw['time_obj'] = pd.to_datetime(df_State_raw['time_str'])
    df_State_raw['min_obj'] = df_State_raw['time_obj'].apply(
            lambda x: x.time().strftime('%M:%S.%f')[:-4])
    df_State_raw['date_time'] = pd.to_datetime(df_State_raw['Date'])
    df_State_raw['date_year'] = df_State_raw['date_time'].map(lambda x: x.year)
    df_State_raw['Seed'] = df_State_raw['Seed'].fillna(value='')
    df_State_raw['seed_time_cleanup'] = df_State_raw['Seed'].apply(
        lambda x: re.sub("[^0-9\.\:]", "", x))
    df_State_raw['seed_time_split'] = df_State_raw['seed_time_cleanup'].apply(
            lambda x: str(x).split(":"))
    df_State_raw['seed_time_str'] = df_State_raw['seed_time_split'].apply(
            lambda x: '2000-01-01 00:59:59.99' if len(x[0]) == 0 else ('2000-01-01 00:00:' + x[0]
            if len(x) == 1 else '2000-01-01 00:0' +x[0] + ':' + x[1]))
    df_State_raw['seed_time_obj'] = pd.to_datetime(df_State_raw['seed_time_str'])
    df_State_raw['seed_min_obj'] = df_State_raw['seed_time_obj'].apply(
        lambda x: x.time().strftime('%M:%S.%f')[:-4])
    df_State_raw['seed_time_seconds'] = df_State_raw['seed_time_split'].apply(
            lambda x: 999.9 if len(x[0]) == 0 else (float(x[0])
            if len(x) == 1 else 60 * float(x[0]) + float(x[1])))
    return df_State_raw

# Cleanup and process the CSV files
df_SV = cleanup_SV(df_SV_raw)
df_State = cleanup_state(df_State_raw)

df_SV.to_csv('data/swimming_data_processed.csv')
df_State.to_csv('data/swimming_data_state_processed.csv')